const SCHEMA_SIMPLE_TYPE_NAMES = {
    GROUP_TYPE_ID:"GroupType.ID"
}

const SCHEMA_SIMPLE_TYPE_RESTRICTION_BASE = {
    COMMON_ID_TYPE:"common:IDType"
}

module.exports.SCHEMA_SIMPLE_TYPE_NAMES = Object.freeze(SCHEMA_SIMPLE_TYPE_NAMES);
module.exports.SCHEMA_SIMPLE_TYPE_RESTRICTION_BASE = Object.freeze(SCHEMA_SIMPLE_TYPE_RESTRICTION_BASE);