const XSD_COMPONENTS_TYPES = {
    GLOBAL_ELEMENT : "GLOBAL_ELEMENT",
    SIMPLE_TYPE : "SIMPLE_TYPE",
    COMPLEX_TYPE : "COMPLEX_TYPE"
}

module.exports.XSD_COMPONENTS_TYPES = Object.freeze(XSD_COMPONENTS_TYPES)