const DIMENSION_AT_OBSERVATION_CONSTANTS = {
    TIME_PERIOD:"TIME_PERIOD",
    ALLDIMENSIONS:"AllDimensions",
    DIMENSION:"Dimension",
    NOT_PROVIDED:"Not Provided"
}

module.exports.DIMENSION_AT_OBSERVATION_CONSTANTS = Object.freeze(DIMENSION_AT_OBSERVATION_CONSTANTS);