const DSD_COMPONENTS_NAMES = {
    DIMENSION:"DIMENSION",
    ATTRIBUTE:"ATTRIBUTE",
    MEASURE:"MEASURE",
    TIME_DIMENSION:"TIME_DIMENSION"
}
const DSD_COMPONENTS_REPRESENTATION_NAMES = {
    TEXT_FORMAT : "TEXT_FORMAT",
    ENUMERATION_FORMAT : "ENUMERATION_FORMAT"
}

module.exports.DSD_COMPONENTS_NAMES = Object.freeze(DSD_COMPONENTS_NAMES);
module.exports.DSD_COMPONENTS_REPRESENTATION_NAMES = Object.freeze(DSD_COMPONENTS_REPRESENTATION_NAMES);