const ITEM_SCHEME_TYPES = {
    CATEGORY_SCHEME:"CATEGORY_SCHEME",
    CONCEPT_SCHEME:"CONCEPT_SCHEME",
    CODE_LIST:"CODE_LIST",
    ORGANISATION_SCHEME:"ORGANISATION_SCHEME",
    AGENCY_SCHEME:"AGENCY_SCHEME",
    DATA_PROVIDER_SCHEME:"DATA_PROVIDER_SCHEME",
    DATA_CONSUMER_SCHEME:"DATA_CONSUMER_SCHEME",
    ORGANISATION_UNIT_SCHEME:"ORGANISATION_UNIT_SCHEME",
    REPORTING_TAXONOMY:"REPORTING_TAXONOMY",
    HIERARCHICAL_CODELIST:"HIERARCHICAL_CODELIST",

    hasProp:function (propertyName){
       return (this.hasOwnProperty(propertyName));
    }
}

export default ITEM_SCHEME_TYPES;