const DATA_COMPONENTS_TYPES = {
    STRUCTURE_ID:"STRUCTURE_ID",
    STRUCTURE_REFS:"STRUCTURE_REFS",
    DATASETS:"DATASETS"
}

module.exports.DATA_COMPONENTS_TYPES = Object.freeze(DATA_COMPONENTS_TYPES);