const COMPONENTS_REPRESENTATION_NAMES = {
    TEXT_FORMAT : "TEXT_FORMAT",
    ENUMERATION_FORMAT : "ENUMERATION_FORMAT"
}

module.exports.COMPONENTS_REPRESENTATION_NAMES = Object.freeze(COMPONENTS_REPRESENTATION_NAMES);