const DIMENSION_AT_OBSERVATION_CONSTANTS = {
    TIME_PERIOD:"TIME_PERIOD",
    ALLDIMENSIONS:"AllDimensions"
}

module.exports.DIMENSION_AT_OBSERVATION_CONSTANTS = Object.freeze(DIMENSION_AT_OBSERVATION_CONSTANTS);