const DSD_COMPONENTS_NAMES = {
    DIMENSION:"DIMENSION",
    ATTRIBUTE:"ATTRIBUTE",
    PRIMARY_MEASURE:"PRIMARY_MEASURE",
    MEASURE_DIMENSION:"MEASURE_DIMENSION",
    TIME_DIMENSION:"TIME_DIMENSION",
    GROUP:"GROUP"
}


module.exports.DSD_COMPONENTS_NAMES = Object.freeze(DSD_COMPONENTS_NAMES);
