const ITEM_SCHEME_TYPES = {
    CATEGORY_SCHEME: "CATEGORY_SCHEME",
    CONCEPT_SCHEME: "CONCEPT_SCHEME",
    CODE_LIST: "CODE_LIST",
    ORGANISATION_SCHEME: "ORGANISATION_SCHEME",
    AGENCY_SCHEME: "AGENCY_SCHEME",
    DATA_PROVIDER_SCHEME: "DATA_PROVIDER_SCHEME",
    DATA_CONSUMER_SCHEME: "DATA_CONSUMER_SCHEME",
    ORGANISATION_UNIT_SCHEME: "ORGANISATION_UNIT_SCHEME",
    REPORTING_TAXONOMY: "REPORTING_TAXONOMY",
    HIERARCHICAL_CODELIST: "HIERARCHICAL_CODELIST",
    METADATA_PROVIDER_SCHEME: "METADATA_PROVIDER_SCHEME",
    VALUE_LIST: "VALUE_LIST"
};

module.exports.ITEM_SCHEME_TYPES = Object.freeze(ITEM_SCHEME_TYPES);