const ACTION_NAMES = {
    UPDATE_TEST_STATE: "UPDATE_TEST_STATE",
    CHILDREN_CANNOT_RUN: "CHILDREN_CANNOT_RUN",
    PASS_IDENTIFIERS_TO_CHILDREN_TESTS: "PASS_IDENTIFIERS_TO_CHILDREN_TESTS",
    UPDATE_COMPLIANT_TESTS_NUMBER: "UPDATE_COMPLIANT_TESTS_NUMBER",
    UPDATE_COVERAGE_NUMBER: "UPDATE_COVERAGE_NUMBER",
    INITIALISE_MODEL: "INITIALISE_MODEL",
    HTTP_RESPONSE_VALIDATED: "HTTP_RESPONSE_VALIDATED"
};

export default ACTION_NAMES;