const ACTION_NAMES = {
    INITIALISE_TESTS_MODEL: "INITIALISE_TESTS_MODEL",

    UPDATE_TESTS_NUMBER: "UPDATE_TESTS_NUMBER",
    UPDATE_COVERAGE_NUMBER: "UPDATE_COVERAGE_NUMBER",
    UPDATE_COMPLIANCE_NUMBER: "UPDATE_COMPLIANCE_NUMBER",
    PASS_IDENTIFIERS_TO_CHILDREN_TESTS: "PASS_IDENTIFIERS_TO_CHILDREN_TESTS",

    UPDATE_TEST_STATE: "UPDATE_TEST_STATE",
    CHILDREN_CANNOT_RUN: "CHILDREN_CANNOT_RUN"
};

export default ACTION_NAMES;