name: node.js CI for SDMX TCK
run-name: Build SDMX TCK
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: sdmx-tck-api
      - run: npm install
        working-directory: sdmx-tck-parsers
      - run: npm install
        working-directory: sdmx-tck-manager
      - run: npm install
        working-directory: sdmx-tck-client
      - run: npm install
        working-directory: sdmx-tck-reporter
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
            
      - name: Extract Tag Name
        id: extract_tag
        run: |
          echo ${{ github.ref_name }}
          echo "::set-output name=TAG_NAME::$(echo ${{ github.ref }} | awk -F'/' '{print $3}')"
